version: '3.9'

volumes:
  common_volume:
    name: ${VOLUME_ID}
    external: false

services:
  documentserver:
    image: "onlyoffice/4testing-documentserver-ee:${DOCSERVER_VERSION}"
    ports:
      - "80:80"
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=secret
      - JWT_HEADER=AuthorizationJwt
  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - common_volume:/usr/share/nginx/html/:rw
  testing_project:
    build: ./
    tty: true
    depends_on:
      - documentserver
      - nginx
    environment:
      - DOCUMENTSERVER=http://documentserver
      - CURRENT_SPEC=${CURRENT_SPEC}
    command: ["./entrypoint.sh"]
    volumes:
      - common_volume:/convert_service_testing/files_tmp/:rw
