version: '3'
services:
  documentserver:
    image: onlyoffice/4testing-documentserver-ie:latest
    ports:
    - "80:80"
    environment:
    - JWT_ENABLED=true
    - JWT_HEADER=AuthorizationJwt
  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./files_tmp/:/usr/share/nginx/html/
  testing_project:
    build: ./
    tty: true
    depends_on:
      - documentserver
      - nginx
    environment:
      - DOCUMENTSERVER=http://documentserver
    command: ["ruby", "./helpers/wait_for_documentserver_start.rb"]
    volumes:
      - ./files_tmp/:/convert_service_testing/files_tmp/
